name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Deploy to gh-pages
        run: |
          git checkout -b gh-pages
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ProfessorJ17/caimeo-shop.git HEAD:gh-pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
