name: My GitHub Action Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use GitHub token
        run: |
          echo "My GitHub token is ${{ secrets.MY_GITHUB_API_TOKEN }}"
        env:
          MY_GITHUB_API_TOKEN: ${{ secrets.MY_GITHUB_API_TOKEN }}
