name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Replace placeholders
        run: |
          sed -i 's@${{ secrets.ENCRYPTED_SIMPLE_USERS }}@${{ secrets.ENCRYPTED_SIMPLE_USERS }}@g' mainframe.html
          sed -i 's@${{ secrets.ENCRYPTION_KEY }}@${{ secrets.ENCRYPTION_KEY }}@g' mainframe.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT }}  # Use PAT instead of github_token
          publish_dir: .
          force_orphan: true
