name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Replace placeholders
- name: Replace placeholders
        run: |
          sed -i "s|ENCRYPTED_SIMPLE_USERS|${{ secrets.ENCRYPTED_SIMPLE_USERS }}|g" mainframe.html
          sed -i "s|ENCRYPTION_KEY|${{ secrets.ENCRYPTION_KEY }}|g" mainframe.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
