name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Replace placeholders
        run: |
          sed -i 's|${{ secrets.ENCRYPTED_SIMPLE_USERS }}|${{ secrets.ENCRYPTED_SIMPLE_USERS }}|g' mainframe.html
          sed -i 's|${{ secrets.ENCRYPTION_KEY }}|${{ secrets.ENCRYPTION_KEY }}|g' mainframe.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
